### ISSUE TITLE
hardhat looking for MainPass, should be RevPass

### ISSUE THREAD

**Issue by ianebeckett** [tamublockchain/revpass#7]
$ yarn hardhat deploy

Nothing to compile
----------------------------------------------------
Deploying MainPass and waiting for confirmations...
An unexpected error occurred:

Error: ERROR processing /home/ian/blockchain_dev/revpass/deploy/01-deploy-revpass.js:
Error: cannot find artifact "MainPass"

$ grep -rl "RevPass" .
./cache/solidity-files-cache.json
./contracts/RevPass.sol
./contracts/ERC4907.sol
./contracts/IRevPass.sol
./artifacts/build-info/e6d705579173daaa81d3e51b9548501d.json
./artifacts/contracts/RevPass.sol/RevPass.json
./artifacts/contracts/IRevPass.sol/IRevPass.json

$ grep -r "MainPass" .
./deploy/01-deploy-revpass.js:    log("Deploying MainPass and waiting for confirmations...")
./deploy/01-deploy-revpass.js:    const Lottery = await deploy("MainPass", {

**Comment by ishandhanani** [comment]
This is an issue with the deploy script. That's why this is not working. See this line in the deploy script 

`const Lottery = await deploy("MainPass", {`

Can you change it to `const RevPass = await deploy("RevPass",{`

That should fix it

**Comment by ishandhanani** [comment]
module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()

    log("----------------------------------------------------")
    log("Deploying MainPass and waiting for confirmations...")
    const name = "RevPass"
    const symbol = "REV"
    const supply = "1000" //example initial value
    const args = [name, symbol, supply]
    const RevPass = await deploy("RevPass", {
        from: deployer,
        args: args,
        log: true,
        // we need to wait if on a live network so we can verify properly
        waitConfirmations: network.config.blockConfirmations || 1,
    })
}
module.exports.tags = ["all", "revpass"]

**Comment by ishandhanani** [comment]
Completed this in the marketplace-issues branch

Returns `Compiled 9 Solidity files successfully`
