### ISSUE TITLE
issues in `listNFT` function

### ISSUE THREAD

**Issue by ishandhanani** [tamublockchain/revpass#8]
1. Owner UIN is a function parameter. Should that already be prefilled from the NFT that the user owns? What if the owner enters an incorrect UIN on their part

**Comment by ishandhanani** [comment]
2. Can we also keep an arbitrary constant set price? Eventually each pass will be rented for (totalSportsPassCost / # of games). Let's just simulate that now

**Comment by ztsalexey** [comment]
1. for owner UIN populating in `listNFT` in `Marketplace` could call `getOwnerUIN(uint256 tokenId)` from `RevPass`

**Comment by zhuodannychen** [comment]
2.

**Comment by ishandhanani** [comment]
Used `IRevPass(nftContract).getOwnerUIN(tokenId)` wherever owner UIN was required
