### ISSUE TITLE
issues with `rentNFT` function

### ISSUE THREAD

**Issue by ishandhanani** [tamublockchain/revpass#9]
1. I dont think the `renter` should be able to set the expiry date. That should come from the `endDateUNIX` parameter in `listNFT`.

A malicious renter could potentially list themselves as a renter for a while effectively giving them control for the entire time

**Comment by ztsalexey** [comment]
Could be coming from `_listingMap[tokenId]`

**Comment by zhuodannychen** [comment]
I think we can remove startDateUNIX. Once the Revpass is listed, students can start renting.
Then yeah we keep endDateUNIX so if someone rents it then the expiry date becomes the endDateUNIX.
If it doesn't get rented out the lender will just press "unlist"

**Comment by ishandhanani** [comment]
1. Changed the marketplace to show enddateUNIX from the `listNFT` function as the expiry date for rental
2. Added `override` to ERC4907.sol because...we changed the uint type?

The old `expiry` is still in as a comment so everyone can be aware of it in future meetings. We can remove it during final code review.
